### ISSUE TITLE
Future maintenance - merge with attranslate?

### ISSUE THREAD

**Issue by fkirc** [pawurb/normit#10]
Hi,

I really like the simple usage of `normit` and I believe that CLI-translation tools are still underrated.
But since `normit` is not maintained anymore, I wrote the new tool `attranslate` that does a similar thing as `normit`: https://github.com/fkirc/attranslate

However, there is still a caveat.
`attranslate` is designed to translate entire apps or websites instead of CLI texts.
In theory, it would be be trivial to extend `attranslate` to translate CLI texts.
In practice, however, it is necessary to configure an API-key before using `attranslate`.
Configuring such an API-key is easy for any serious app or website, but it is tedious if you want to install and run `attranslate` just for a one-off task.
So my question is:

Are you aware of any high-quality translation service that works without any API-key?
Scraping Google Translate or Bing might be doable, but I am not sure whether this is stable or against their terms of service?
If this is doable, then it might be easy to adopt `normit`-functionality for `attranslate`.

**Comment by pawurb** [comment]
Hi. I don't know any free translation API you could use for that.
