### ISSUE TITLE
Normit broken?

### ISSUE THREAD

**Issue by abinash111** [pawurb/normit#3]
Hi,

I don't know javascript therefore I am not able to ascertain the source/nature of the problem. But normit seems to have stopped translating. All I get is 'There seems to be a problem with your internet connection'. I have tried it from two different places. Got the same response.

Could you please look into it?

Thanks a lot for the library! I am using it in an IOT project.

**Comment by nprowler** [comment]
I too am having problems. Seems to have started yesterday. Google Translate website is working.
guess Google might have changed something to the API. :(

I too wanted to thank You for a great node for my Node Red project.

Thanks.

**Comment by pawurb** [comment]
Looks like something must have changed on the google side. I will look into it today/tomorrow.

**Comment by pawurb** [comment]
I am sorry but looks like the api's endpoints I was using are blocked and I will no longer be able to scrape them. You can look into official google translate api if you need something similar.

**Comment by abinash111** [comment]
Thanks a lot for your efforts.

The tool was awesome! :)
