### ISSUE TITLE
Have APIs changed again?

### ISSUE THREAD

**Issue by enkiv2** [pawurb/normit#4]
This issue affects both termit and normit.

In normit, I get the following behavior:

    $  normit en es hello
    NORMIT: There seems to be a problem with your internet connection

In termit, I get the following behavior:

    $  termit en es hello
    /usr/lib/ruby/gems/2.3.0/gems/termit-2.13.0/lib/termit/text_response_handler.rb:22:in `extract_translation': undefined method `split' for nil:NilClass (NoMethodError)
            from /usr/lib/ruby/gems/2.3.0/gems/termit-2.13.0/lib/termit/text_response_handler.rb:13:in `call'
            from /usr/lib/ruby/gems/2.3.0/gems/termit-2.13.0/lib/termit/text_translator.rb:13:in `call'
            from /usr/lib/ruby/gems/2.3.0/gems/termit-2.13.0/lib/termit/main.rb:10:in `translate'
            from /usr/lib/ruby/gems/2.3.0/gems/termit-2.13.0/bin/termit:10:in `<top (required)>'
            from /usr/bin/termit:23:in `load'
            from /usr/bin/termit:23:in `<main>'

**Comment by pawurb** [comment]
Please checkout the project status in readme. It is no longer functional.
