### ISSUE TITLE
Cannot Translate

### ISSUE THREAD

**Issue by saiprasath-swaas** [pawurb/normit#8]
NORMIT: There seems to be a problem with your internet connection, or the language codes you provided are invalid

**Comment by pawurb** [comment]
Thanks for reporting it but I am no longer actively maintaining the project. It uses private APIs to get translations so they might have changed. PRs fixing it are welcome.

**Comment by mixn** [comment]
@pawurb Which API is normit using? It seems like a great tool. I just ran into this exact issue which lead me to seeing that it is no longer actively maintained. 

Just a small heads-up: it’d be great to be able to tell/see this from the `README` (and ideally right away).

In the `README`’s current state, it does seem like a fully functional and maintained project (I didn’t peak at the commit history). Maybe archive the project or add a disclaimer to `README`? 🙂

Not trying to nit-pick, just thinking out loud. 

Thanks for your work on this… maybe you’ll consider picking it up again. Hehe. 🙌

**Comment by pawurb** [comment]
@mixn it uses private Bing translator APIs. They might have changed or they added some way to prevent scraping. I have little time to look into it now.

**Comment by fkirc** [comment]
I would also be interested to use an API like this for `attranslate`, but I wrote a separate issue because this might be out of scope: https://github.com/pawurb/normit/issues/10
